export interface Specialization {
  code: string;
  name: string;
  category: string;
  color: string;
}

export const MEDICAL_SPECIALIZATIONS: Specialization[] = [
  { code: "I10-I15", name: "Cardiology", category: "Internal Medicine", color: "indigo" },
  { code: "E10-E14", name: "Endocrinology", category: "Internal Medicine", color: "amber" },
  { code: "C00-D48", name: "Oncology", category: "Surgery/Medicine", color: "rose" },
  { code: "N00-N99", name: "Nephrology", category: "Internal Medicine", color: "blue" },
  { code: "J00-J99", name: "Pulmonology", category: "Internal Medicine", color: "cyan" },
  { code: "K00-K93", name: "Gastroenterology", category: "Internal Medicine", color: "emerald" },
  { code: "G00-G99", name: "Neurology", category: "Internal Medicine", color: "purple" },
  { code: "M00-M99", name: "Rheumatology", category: "Internal Medicine", color: "violet" },
  { code: "F01-F99", name: "Psychiatry", category: "Mental Health", color: "pink" },
  { code: "O00-O99", name: "Obstetrics & Gynecology", category: "Surgery/Medicine", color: "fuchsia" },
  { code: "P00-P96", name: "Pediatrics", category: "Medicine", color: "orange" },
  { code: "S00-T88", name: "Trauma & Orthopedic Surgery", category: "Surgery", color: "slate" },
  { code: "H00-H59", name: "Ophthalmology", category: "Surgery", color: "sky" },
  { code: "L00-L99", name: "Dermatology", category: "Medicine", color: "yellow" },
  { code: "R00-R99", name: "Emergency Medicine", category: "Medicine", color: "red" },
  { code: "Z00-Z99", name: "Preventive Medicine", category: "Public Health", color: "teal" },
  { code: "A00-B99", name: "Infectious Diseases", category: "Medicine", color: "lime" },
  { code: "D50-D89", name: "Hematology", category: "Medicine", color: "darkred" },
  { code: "Q00-Q99", name: "Medical Genetics", category: "Medicine", color: "indigo" },
  { code: "V01-Y98", name: "Forensic Medicine", category: "Medicine", color: "zinc" },
  { code: "N40-N51", name: "Urology", category: "Surgery", color: "blue" },
  { code: "J45", name: "Allergy & Immunology", category: "Medicine", color: "orange" },
  { code: "G47", name: "Sleep Medicine", category: "Medicine", color: "darkblue" },
  { code: "I20-I25", name: "Interventional Cardiology", category: "Surgery/Medicine", color: "rose" },
  { code: "M15-M19", name: "Physical Medicine & Rehab", category: "Medicine", color: "green" },
  { code: "H60-H95", name: "Otolaryngology (ENT)", category: "Surgery", color: "cyan" },
  { code: "C50", name: "Surgical Oncology", category: "Surgery", color: "rose" },
  { code: "I60-I69", name: "Vascular Surgery", category: "Surgery", color: "red" },
  { code: "G04", name: "Neurocritical Care", category: "Medicine", color: "violet" },
  { code: "K50-K52", name: "Colorectal Surgery", category: "Surgery", color: "emerald" },
  { code: "E03", name: "Nuclear Medicine", category: "Imaging", color: "yellow" },
  { code: "R90-R94", name: "Diagnostic Radiology", category: "Imaging", color: "gray" },
  { code: "Z51.5", name: "Palliative Care", category: "Medicine", color: "stone" },
  { code: "M80-M81", name: "Geriatric Medicine", category: "Medicine", color: "brown" },
  { code: "T36-T50", name: "Clinical Pharmacology", category: "Medicine", color: "teal" },
  { code: "J44", name: "Critical Care Medicine", category: "Medicine", color: "orange" },
  { code: "P07", name: "Neonatology", category: "Medicine", color: "pink" },
  { code: "I26", name: "Vascular Medicine", category: "Medicine", color: "red" },
  { code: "B20-B24", name: "HIV/AIDS Medicine", category: "Medicine", color: "rose" },
  { code: "G40", name: "Epileptology", category: "Medicine", color: "purple" },
  { code: "K70-K77", name: "Hepatology", category: "Medicine", color: "orange" },
  { code: "I05-I09", name: "Pediatric Cardiology", category: "Medicine", color: "pink" },
  { code: "F32", name: "Addiction Psychiatry", category: "Mental Health", color: "indigo" },
  { code: "M32", name: "Sports Medicine", category: "Medicine", color: "green" },
  { code: "L40", name: "Dermatopathology", category: "Medicine", color: "yellow" },
  { code: "N17-N19", name: "Transplant Nephrology", category: "Medicine", color: "blue" },
  { code: "K21", name: "Upper GI Surgery", category: "Surgery", color: "emerald" },
  { code: "J30", name: "Rhinology", category: "Surgery", color: "cyan" },
  { code: "H35", name: "Vitreoretinal Surgery", category: "Surgery", color: "sky" },
  { code: "G20", name: "Movement Disorders", category: "Medicine", color: "violet" },
  { code: "E66", name: "Bariatric Surgery", category: "Surgery", color: "amber" },
  { code: "Z00.1", name: "Adolescent Medicine", category: "Medicine", color: "orange" }
];
